# Generated by Django 5.1.4 on 2024-12-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0002_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigninTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
